before_install:
- openssl aes-256-cbc -K $encrypted_eb2c67d49252_key -iv $encrypted_eb2c67d49252_iv
  -in travis.enc -out travis -d
- echo "ls travis -ls"
- chmod 600 travis
- echo "ls travis -ls"
- mv travis ~/.ssh/id_rsa
language: node_js
node_js:
- 11.6.0
services:
- docker
branches:
  only:
  - master
env:
  global:
  - REMOTEAPPDIR=/var/www/light-it-08.tk/
  - REMOTEUSER=usr01
  - REMOTEHOST=188.166.54.169
  - PORT=54231
  - DOCKER_PASSWORD=qwerty123
  - DOCKER_USERNAME=6633
  - DOCKER_REPO=angular-ssr
script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- npm install
- npm run build:ssr
- chmod 777 -R ./dist/
- echo "ls ./dist/ -la"
- docker build --tag=angular_ssr .
- docker tag angular_ssr 6633/angular-ssr:angular_ssr
- bash ./scripts/push.sh
